### ISSUE TITLE
请大家切勿在别人的仓库内过度使用中文和玩国内梗

### ISSUE THREAD

**Issue by ZeroAurora** [kelseyhightower/nocode#1089]
（乱发言论的人，请补补 Github 社区指南）
> What is not allowed?
>https://help.github.com/articles/github-community-guidelines/#what-is-not-allowed

这是一个国际板块，请不要过度使用中文和玩梗，老外理解很困难的
（可以玩一些代码方面的梗XD）
我找到一个中文版： https://github.com/justjavac/nocode
请不要惹到别人删 Repo 的境界，都是 Github 的人，人与人间的尊重还是要有。
谢谢配合！玩得愉快

# 那些广告机们，请你们务必停一停，这里不是贴吧！！！！！
# 不要丢脸丢到国外！！！！！！！！！！

**Comment by myd7349** [comment]
Agreed!

**Comment by ZeroAurora** [comment]
# 那些广告机们，请你们务必停一停，这里不是贴吧！！！！！

**Comment by DavinQi** [comment]
说的对 。。。

**Comment by DavinQi** [comment]
老外会当做中国人随便吐痰一样，看待中国人随意在网上发一些无价值的垃圾评论。

**Comment by hwk603** [comment]
+1

**Comment by ahjsrhj** [comment]
```

```

**Comment by ZeroAurora** [comment]
@DavinQi 我就怀疑有一些人想要丢脸丢到国外，比如 #1086 #1071 etc.

**Comment by chai2010** [comment]
过来吐口痰

**Comment by jlcon** [comment]
What is not allowed?并没有讲不允许玩梗啊，这个项目本身就是作者一个玩笑恶搞一下

**Comment by ZeroAurora** [comment]
@jlcon 尽量别用，因为本身这个项目就不是国人开的

**Comment by Fuaveax** [comment]
好多中文并没有恶意  这也会惹到国外友人？

**Comment by ZeroAurora** [comment]
@Fuaveax  不知你是否看到过这些 #1108 #1083 #1071 #1064 #1058

**Comment by ZeroAurora** [comment]
@chai2010 随意，唯一要求是自己舔回去
你对我无理，我也无能为力。能干什么？？？

**Comment by chai2010** [comment]
再吐一口

**Comment by jlcon** [comment]
@ZeroAurora 你走吧，你不适合干程序员这个职业，你懂外国程序员的幽默感么？你知道外国程序的脑洞不？在一个有趣的项目里面发点欢乐的评论，你还让上升到吐痰这么恶心的字眼，还让人甜回去。正如你说的，在国际场合不要挑起内部纷争，要怪就怪今日头条吧。

**Comment by ZeroAurora** [comment]
@jlcon 你也看到了他对我的言论。

**Comment by ZeroAurora** [comment]
@jlcon 已删除，如有不适实属抱歉

**Comment by jlcon** [comment]
@ZeroAurora 大家都没有恶意，只是想快乐一下而已

**Comment by zacksleo** [comment]
@see https://github.com/zacksleo/nocode-cn/issues

**Comment by myd7349** [comment]
我觉得 #1089 是在善意的提醒而已。
1. 我并不觉得在 GitHub 不用中文就是文化不自信的表现。如果真是这样的话，用英文编程是否也说明我们不自信呢？（况且，PS、IMO 不都是英文简写吗？）
2. 我觉得在 GitHub 上最好不要谈政治，如果 GitHub 再次被封，也是广大中国程序员蒙受损失吧？所以，涉及政治立场的话，我觉得还是少讲为好。我觉得 #1045 这样的标题还是少用为妙。

**Comment by kingflight** [comment]
@ZeroAurora 如果你想设定一些新的贡献规则，你可以fork这个repo，然后修改CONTRIBUTING.md，因为这个repo的CONTRIBUTING.md已经写的很清楚了。
> All changes are welcome as long as no code is involved. If you run into any bugs, please file an issue and explain how that was even possible.

**Comment by ZeroAurora** [comment]
@kingflight “但是没说可以随便水贴啊”
“但是提PR可以啊(滑稽)”

**Comment by kaelzhang** [comment]
孩子们，还是多花点时间写代码吧，这个 issue 可以关掉了。人家老 K 也是工作之余来娱乐一下，大家别这么认真。

**Comment by ZeroAurora** [comment]
Closed
