### ISSUE TITLE
Қазақ тілін қолдау

### ISSUE THREAD

**Issue by Khangeldy** [kelseyhightower/nocode#1244]
Қазақ тілінде жазылған шрифтерде `ҚІӘҢҒҮҰӨҺ` сияқты әріптерді әдемсіз болып шығып тұр.

**Comment by Zhomart** [comment]
Қажеті жоқ, "жақында" қазақ тілі латын әліпбиіне өтеді.

**Comment by Khangeldy** [comment]
Codeo чатындағы Жомартсың ба?
