### ISSUE TITLE
Can we use Prettier for formatting nocode?

### ISSUE THREAD

**Issue by trivikr** [kelseyhightower/nocode#125]

**Comment by petermbenjamin** [comment]
I believe you may need to open an issue in Prettier's project to build a plugin for formatting nocode.

**Comment by trivikr** [comment]
Prettier already supports formatting nocode

**Comment by petermbenjamin** [comment]
Great.
Another concern I have with this is that *Node.js* support is not fully baked yet (per release notes)
![screenshot 2018-02-06 at 9 03 02 pm](https://user-images.githubusercontent.com/6811830/35904075-9d75c8ac-0b96-11e8-9a88-8452bedbead6.png)

**Comment by trivikr** [comment]
Oh, that's sad.
JavaScript is the most popular programming language in the world right now. This will seriously impact nocode's usage!

Is Node.js support planned in future versions?
