### ISSUE TITLE
Blockchain Support

### ISSUE THREAD

**Issue by nmd1** [kelseyhightower/nocode#1258]
This code seems very promising! In fact the underlying structure could be incorporated into a new cryptocurrency. Hear me out:

In order to successfully mine a new block and complete a transaction with "NoCoin" you would have to use your special "NoHash" function (used near the beginning of your program):

```

```
The potential here is huge. I **highly** recommend forking a new repo and pursuing this.

**Comment by filippocld** [comment]
This way the value of the coin would be _**nothing**_! EXCELLENT

**Comment by ghiliweld** [comment]
ICO when?

**Comment by dschreiber** [comment]
Release notes at https://github.com/kelseyhightower/nocode/releases indicate Blockchain support already exists.

**Comment by nmd1** [comment]
Thank you! I've made _millions_ with NoCoin, thanks to this year old idea!
