### ISSUE TITLE
so I deleted all code from my workmate' computer and now he is unhappy

### ISSUE THREAD

**Issue by jjsty1e** [kelseyhightower/nocode#1324]
why he keeps his code as no code is the best?

**Comment by antgly** [comment]
You did it! Thanks. I've been trying to figure this out all day for hours...

**Comment by fymeven** [comment]
soyou are fire now

**Comment by boris1993** [comment]
Well, different people have different thoughts. Better not to force people believe something they don't.

**Comment by Jaggle** [comment]
@boris1993 just jokes, will never do that.

**Comment by boris1993** [comment]
@Jaggle I'm joking too 😆
