### ISSUE TITLE
Make it run on the blockchain

### ISSUE THREAD

**Issue by manojlds** [kelseyhightower/nocode#134]
Doesn't look to be blockchain compatible.

**Comment by petermbenjamin** [comment]
As of v1.0.0, nocode runs on the blockchain.
Please, see the release notes: https://github.com/kelseyhightower/nocode/releases/tag/1.0.0
![screenshot 2018-02-06 at 9 03 02 pm](https://user-images.githubusercontent.com/6811830/35903516-6618323e-0b94-11e8-9705-1118e9522bd6.png)

**Comment by petermbenjamin** [comment]
Duplicate of #81
