### ISSUE TITLE
Nothing is erverything.

### ISSUE THREAD

**Issue by Dorbmon** [kelseyhightower/nocode#1355]
It's the best way for us to code.No code means no bug!!!!!

**Comment by kaishin** [comment]
Too vague. Maybe provide steps to _not_ reproduce?

**Comment by Dorbmon** [comment]
NO NO NO...Your are wrong.You just need to stay in front of your computer thinking about what you want to do and believe that everything had been done so that you just need to sleep.And then you sleep.

**Comment by Dorbmon** [comment]
No code means that you shouldn't do anything.
