### ISSUE TITLE
Any logo ideas?

### ISSUE THREAD

**Issue by trivikr** [kelseyhightower/nocode#140]
The project nocode went viral and is now pretty popular.
Any ideas for the logo?

**Comment by trivikr** [comment]
How about this?
<img width="106" alt="screen shot 2018-02-07 at 12 18 27 am" src="https://user-images.githubusercontent.com/16024985/35905581-880ebca2-0b9c-11e8-98ab-1ff4f60d0466.png">

**Comment by aa333** [comment]
I've a better idea, how about this:
