### ISSUE TITLE
How tf this repository have 10k stars?

### ISSUE THREAD

**Issue by dikiaap** [kelseyhightower/nocode#1449]
I’m out of the loop of this trending. Are there any discussion links like Reddit or Hacker News or articles that related to Nocode?

Edit: Found this one https://news.ycombinator.com/item?id=16321166

**Comment by blackjyn** [comment]
NO
Because NO CODE is needed
what are you going to discussed about with no code?

**Comment by dikiaap** [comment]
I will discuss about nothing of nocode.
