### ISSUE TITLE
It's a shame to see so many Chinese characters

### ISSUE THREAD

**Issue by DanteAndroid** [kelseyhightower/nocode#1466]
English is the general language for Github. And the author of this repository is **NOT** Chinese, I don't get why so many Chinese getting so high here.
I am Chinese, and I feel embarrassed about this.

**Comment by SophieYuan12** [comment]
hi,you are too serious

**Comment by azumia** [comment]
要不要这么自卑啊兄弟，动不动就shame

**Comment by tianlanhai** [comment]
能明白你的心情，就像中国清朝，一直还以为和古代一样，文化、发明、经济等都领先全世界的时候，对外国也是shame。
Can understand your feelings, just like China's Qing Dynasty, has always thought that as in ancient times, culture, inventions, economy, etc. all lead the world, it is also a shame to foreign countries.

**Comment by sushushu** [comment]
2333333

**Comment by connectkushal** [comment]
agreed, चिंकी चूतिये है

**Comment by chbdetta** [comment]
It's rude to talk in non-general languages because it is essentially preventing foreign speaker from joining the conversation.

**Comment by pczy** [comment]
Реальное имя,Opozita reale e sistemit të emrit

**Comment by William-Python-King** [comment]
No shame buddy! Google translation is getting more intelligent with machine learning. We know what you said. Language won't be a barrier to GitHubers.

**Comment by tete1030** [comment]
@azumia @tianlanhai It's only about constructive conversations, not your pathetic confidence.

**Comment by William-Python-King** [comment]
@tete1030 Hi, don't be serious.

**Comment by connectkushal** [comment]
:om: talking in a foreign lang is one thing. Writing sh*te is another. Shows their sad mentality

**Comment by blackcatpolice** [comment]
@DanteAndroid  Why the Chinese people can use English talking on here , but you don't use Chinese talking to them , do you realy have no idea?

**Comment by unstoppaul1982** [comment]
shame 你妹啊， 说明广大码农属国人最闲

**Comment by phannam1412** [comment]
xin chào, tao là Việt Nam và tao cũng không thích điều này

**Comment by DanteAndroid** [comment]
@connectkushal Well, peace is nice, but I think some people's behavior has become some trouble to others, so just a *kind* reminder.

**Comment by DanteAndroid** [comment]
@blackcatpolice Nice question. I just want to talk about this problem with others, so with English. And I don't think they are unable to understand it because they came to this repository (which is written in English).

**Comment by duyanning** [comment]
> 
> 
> English is the general language for Github. And the author of this repository is **NOT** Chinese, I don't get why so many Chinese getting so high here.
> I am Chinese, and I feel embarrassed about this.

你有这样的想法，竟然还用英语写出来，作为你的同胞，也让我觉得挺羞耻的

**Comment by QuasiLegendre** [comment]
Shame on you, not Chinese. Frick your mf mouth up.

**Comment by SimpleIto** [comment]
太搞笑了，说母语真就自己开始shame起来了呗？一个搞笑项目在这儿上纲上线，跪外国爹跪得还舒服吗？
英语是行规推荐用语，但没任何条目限制其他语言的出现，真正和平友好的氛围应该尊重任何语言的发言，至于需不需要花时间理解是你自己的选择，而不是在这儿阴阳怪气自己的母语。
可别你是国人了，我都嫌丢人，居然还能看到这样的言论。

**Comment by DanteAndroid** [comment]
It's a technical website, not a forum. So language matters. Of course, every language should be respected, but so do people. You see, there's no other language except English and Chinese. Why other people choose English instead of their own one? What impression will Chinese leave to others?

**Comment by SimpleIto** [comment]
> It's a technical website, not a forum. So language matters. Of course, every language should be respected, but so do people. You see, there's no other language except English and Chinese. Why other people choose English instead of their own one? What impression will Chinese leave to others?

你自己也说了这个是技术网站，那你为什么你不用英语来diss这纯娱乐项目呢？大家也都纯娱乐而已，而不是让你借此机会在这shame过去shame过来。所以我开头就讲，这是个搞笑项目，没必要上纲上线。

退一步就算不是娱乐项目，我也提了英语是行规用语，能用英文大家无障碍交流最好，但即便出现了其他语言也不应该成为你diss的理由。要是有个德语issue下面有人说"嘿，我也是德国人，在GitHub就用英语，我就不明白你为什么要在这儿逼逼赖赖，我看到这些德文都感到害臊"，那可得笑死。

你觉得这是在为国人遮羞吗？不，别人只会从你的言论感到深深的劣根性。
