### ISSUE TITLE
NoCode Rewards program

### ISSUE THREAD

**Issue by trivikr** [kelseyhightower/nocode#150]
Hi,

From [CONTRIBUTING.md](https://github.com/kelseyhightower/nocode/blob/master/CONTRIBUTING.md), it appears that it's difficult to find bugs/issues in nocode.

Of course we know that **no code** is perfect. How about creating a NoCode Rewards program to reward those who find bugs with nocode. This can be similar to [Chrome Rewards](https://www.google.com/about/appsecurity/chrome-rewards/)

Regards,
Trivikram

**Comment by tj-commits** [comment]
Rewards would be against the law of no code as someone would have to code the program. it would only sort of make sense if the rewards gave you 0 points for which you can get free nothingness for 0 points
