### ISSUE TITLE
｡◕ ‿ ◕｡

### ISSUE THREAD

**Issue by fridzema** [kelseyhightower/nocode#1596]
.'"'.        ___,,,___        .'``.
: (\  `."'"```         ```"'"-'  /) ;
 :  \                         `./  .'
  `.                            :.'
    /       __)        __)      \

   |        (●)       (●)        |
   |         /         \         |
   |       /             \       |
    \     |      .-.      |     /
     `.   | . . /   \ . . |   .'
       `-._\.'.(     ).'./_.-'
           `\'  `._.'  '/'
             `. --'-- .'
               `-...-'

**Comment by mxchange** [comment]
I just tried to ran this piece of code, and it did nothing, A+

**Comment by fridzema** [comment]
Aaah this is desired behavior, i am closing this for now...
