### ISSUE TITLE
Running `` gives no output

### ISSUE THREAD

**Issue by zakkor** [kelseyhightower/nocode#1599]
## What version of nocode are you using (run ` `)?
```

```

## Does this issue reproduce with the latest release?
Yes.

## What operating system and processor architecture are you using?
Ubuntu 16.04

## What did you do?
```

```
## What did you expect to see?
```

```
## What did you see instead?
```

```

**Comment by SevastyanDark** [comment]
Good issue, need to fix it.

**Comment by azjezz** [comment]
have you tried this : 
```

```
you should see the following output : 
```

```

**Comment by QIvan** [comment]
I think the issue can be closed because the output is exactly the same as expected.

**Comment by iamandrewluca** [comment]
Operating system should be
```
```

**Comment by zakkor** [comment]
@iamandrewluca's comment helped me diagnose the issue:
For everyone else that encounters this issue coming from google, here's what I did:
I ran this command:  
```

```

If it gives the following output, it means the issue is fixed:
```

```

**Comment by iamandrewluca** [comment]
@zakkor Glad I could help 😀

**Comment by mohsinulhaq** [comment]
``

**Comment by mohsinulhaq** [comment]
``

**Comment by mohsinulhaq** [comment]
`
`

**Comment by mohsinulhaq** [comment]
`

`

**Comment by mohsinulhaq** [comment]
`

         

`

**Comment by mohsinulhaq** [comment]
`                                                                                                                                                                        `

**Comment by mohsinulhaq** [comment]
`&nbsp;`

**Comment by mohsinulhaq** [comment]
<code>

</code>

**Comment by mohsinulhaq** [comment]
<code>&#13;&#10;</code>

**Comment by mohsinulhaq** [comment]
`<br/>`

**Comment by mohsinulhaq** [comment]
<br/>
