### ISSUE TITLE
Lucu reponya

### ISSUE THREAD

**Issue by mfaridzia** [kelseyhightower/nocode#1709]
Repo terngakak ini ✌️

**Comment by rahmatullah5** [comment]
Programmer punya selera humur yang bagus wkwkw

**Comment by dikiaap** [comment]
Benar. Ada juga bahasa pemrograman yang lain yang mungkin lucu dan sedikit mengganggu. C plus  Equality: https://github.com/ErisBlastar/cplusequality. Dan software ini juga, mungkin sudah familiar: https://github.com/nvbn/thefuck

**Comment by mfaridzia** [comment]
@rahmatullah5  wkwk yg bikin issues nya juga pada kreatif wkwk

**Comment by mfaridzia** [comment]
@dikiaap Waduh asem haha ngakak baca readmenya :v
