### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by marcocast** [kelseyhightower/nocode#174]
It works fine on unix and mac, but.....

**Comment by isc30** [comment]
try replacing your environment variables that look like this:
```
```

with this (windows specific):
```
```

**Comment by marcocast** [comment]
Thanks isc30,

Now it seems to work better (even though i had to slightly change the command like this : )

**Comment by paraita** [comment]
Thanks for the tip, you just saved my day in prod !

**Comment by StefanScherer** [comment]
Thanks, works on Windows. But I still have a problem in WSL.

**Comment by StefanScherer** [comment]
Found it.
```
```
