### ISSUE TITLE
how to install this on my calculator?

### ISSUE THREAD

**Issue by agungyuliaji** [kelseyhightower/nocode#1741]
currently i'm coding on my new machine, but how to install `nocode`?
i've tried nothing but still not installed 🙏 

this is 👇 my machine, anyone can give a clue?
![](http://promidatafiles.blob.core.windows.net/catalog/A118-827903.jpg)

**Comment by moizalicious** [comment]
@agungyuliaji have you tried removing the battery before installing. `nocode` is not very compatible with power. The above device seems to be solar powered so I suggest not letting any light through the panel on the top left-hand corner.

**Comment by pokiz** [comment]
Thanks, it fixed it for me !

**Comment by agungyuliaji** [comment]
@moizalicious I've done as you say. but still can not be installed 😞 ... what OS are you using?
I installed OSX High Sierra to my calculator. hmmmm probably it's a compatibility issue

**Comment by moizalicious** [comment]
Ahh, I'm using a Linux Distro. This is the device that I am currently running my nocode application on. It seems to work fine for me.

![image](https://user-images.githubusercontent.com/25219255/36295571-7363424a-130e-11e8-861b-b317c6ef1925.png)

**Comment by agungyuliaji** [comment]
ahhhhhh i see, that is powerfull device!
but just have flaws the power energy dropped to -100% after chewed

**Comment by agungyuliaji** [comment]
it fixed by no PR, awesome!!!!
