### ISSUE TITLE
Docker image needed

### ISSUE THREAD

**Issue by hypersleep** [kelseyhightower/nocode#18]
Hi! I'm want to run nocode with millions of containers on huge scale. And because now configuration and build processes are very hard to repeat on big number of nodes i think docker support will be very desired!

**Comment by vitroth** [comment]
Once an image is published, please tag it with latest.  Please also announce all image updates, so we can update our deployed apps.  Hopefully we won't have to rollback from latest though, I heard somewhere that is problematic...

**Comment by jjzabkar** [comment]
Looks like this issue is resolved via https://github.com/kelseyhightower/nocode/commit/ed6c73fc16578ec53ea374585df2b965ce9f4a31.

**Comment by Silence2012** [comment]
LGTM

**Comment by chai2010** [comment]
`docker pull kelseyhightower/nocode`

**Comment by hypersleep** [comment]
Fixed now! Thanks!
