### ISSUE TITLE
Where is the code???

### ISSUE THREAD

**Issue by rclai** [kelseyhightower/nocode#1822]

**Comment by 1ReimuReimu1** [comment]
Did you not get the joke

**Comment by Dzenly** [comment]
The code is deleted for security reasons. Actually there is so many insider's info in issue descriptions, I am afraid it is a big hole in security :(

**Comment by BenBoudreau-AI** [comment]
Look harder

**Comment by rclai** [comment]
Of course I got the joke..

**Comment by stephentoth** [comment]
What joke? Security is seriously serious business.

**Comment by rclai** [comment]
Seriously?

**Comment by stephentoth** [comment]
Seriously. I use no code all the time for my secure applications and it works great.
