### ISSUE TITLE
Support needed for Nokias

### ISSUE THREAD

**Issue by PeteMcGreete** [kelseyhightower/nocode#1878]
It is a revolutionary market with untapped potential, please add support for it and I will pay 3 GRLC to anyone who does it.

**Comment by drawcard** [comment]
Nocode was in fact first developed by Nokia, as a timewaster app similar to Snake. However the budget blew out really quickly during the R&D phase and Snake's development team quickly took all the resources away. 

Nocode was then sold off to Microsoft for a record $1.5bn, who then developed Nocode Alpha v0.1. This got stuck in development hell for a good decade or so before the community rallied around @kelseyhightower who led the charge to get it open-sourced for the good of mankind, so devs around the world could tackle some of the more major flaws inside that were causing havoc with 90%+ of Intel CPUs globally.

Development is still progressing of course and a PR is in the works to fix these flaws.

PS. 3 GRLC probably won't cover the dev team's costs, they need to buy a ton of GPU's for testing. 3.5 might do it though.
