### ISSUE TITLE
Open sauce?

### ISSUE THREAD

**Issue by drawcard** [kelseyhightower/nocode#1911]
Help I've been trying to use nocode to open sauce for hours. What am I doing wrong?

![image](https://user-images.githubusercontent.com/1435638/36401796-c230b2f4-1629-11e8-882d-df41399c4b03.png)

**Comment by drawcard** [comment]
Did that, but it's still closed sauce unfortunately. Might have to take it back to the supermarket and review the licencing information.

**Comment by bvanvliet** [comment]
Hmmm. Have you tried opening the sauce?

**Comment by drawcard** [comment]
Cheers, that worked!
