### ISSUE TITLE
NoCodeCon 2018!

### ISSUE THREAD

**Issue by drawcard** [kelseyhightower/nocode#1912]
Who's attending this year!? I'm really excited by the speaker list: 

```



```

**Comment by bvanvliet** [comment]
As far as I know, NoBody. 

Dr. Hanus P NoBody to be more precise.

**Comment by benny-innofaith** [comment]
I too will not be attending. 💃

**Comment by 16patsle** [comment]
Why are there no tickets?

**Comment by drawcard** [comment]
The event promoter is also starting to panic because no venue has been booked... and it's happening in 0 days time...

**Comment by YouriAckx** [comment]
There are `0` out of `0` seat(s) available. Hurry up.
