### ISSUE TITLE
PearlJam.c in /nocode/lib/ not compiling correctly

### ISSUE THREAD

**Issue by drawcard** [kelseyhightower/nocode#1922]
Every time I try to compile it, I get this image:

![image](https://user-images.githubusercontent.com/1435638/36426534-2d410f92-169a-11e8-8a6c-e986bc0fbccd.png)

**Comment by bvanvliet** [comment]
Looks like a NoCode _NoBug_ triggered the iPhone camera's rapid exposure function. This iPhone clearly belonging to someone at a postmodernist vegan house-party.

**Comment by drawcard** [comment]
Thats why I can smell deep fried cabbage balls.
