### ISSUE TITLE
 **** No Code, now available on Google Play Store ****

### ISSUE THREAD

**Issue by adubaldo** [kelseyhightower/nocode#1942]
Finally! "No Code" is now available on Android platform!

You can download "No Code" app from Google Play.
- 100% devices compatibility!
- secure coding
- no ads
- no registration required

link: https://play.google.com/store/apps/details?id=com.secure.nocode.nocode

--------------------------------------------------------
SHA256 : 
MD5: 

Thank you!

**Comment by fabriren** [comment]
App installed.
It's perfect, no issues on P9.
5 stars.

**Comment by adubaldo** [comment]
Now pull req
