### ISSUE TITLE
git: 'noclone' is not a git command

### ISSUE THREAD

**Issue by elwinarens** [kelseyhightower/nocode#1975]
I'm trying to create no clone using git, but i'm getting:

```
git: 'noclone' is not a git command. See 'git --help'.
```

I couldn't find the `noclone` command in the help, even though it says i should look for it there.

Please help.

**Comment by genacrys** [comment]
Instead of `git noclone`, you should try:
```
```
You will see following output:
```
```

**Comment by rakeshjuyal** [comment]
Thanks @genacrys . That worked.

_If above solution doesn't work then you might have to restart your system._

**Comment by elwinarens** [comment]
Thanks, fixed it. Closing.
