### ISSUE TITLE
Could not execute docker build with Dockerfile

### ISSUE THREAD

**Issue by sasukeh** [kelseyhightower/nocode#2053]
I've gotta Docker issue like following logs.

```
PS C:\User\<username>\Code\nocode> docker build .
Sending build context to Docker daemon  84.48kB
Step 1/1 : FROM scratch
 --->
No image was generated. Is your Dockerfile empty?
```

```
PS C:\Users\<username>\Code\nocode> Docker pull scratch
Using default tag: latest
Error response from daemon: 'scratch' is a reserved name
```

### Environment
- OS: Windows 10 Enterprise
- Docker: Docker version 18.03.0-ce-rc1, build c160c73

Is there any suggestion to execute docker build properly?

**Comment by sasukeh** [comment]
I just realized this Dockerfile works fine.
"Is your Dockerfile empty?" -> "Yes, that is correct because of nocode"

**Comment by kaushalendrakumar** [comment]
I have a fully written dockerfile but it does not work
`[root@master dockerfiles]# pwd
/root/dockerfiles
[root@master dockerfiles]# ll
total 4
-rwxrwxrwx. 1 root root 577 May 24 10:18 Dockerfile
[root@master dockerfiles]# cat Dockerfile
FROM centos
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
[root@master dockerfiles]# db -t kaushal_centos:1.0 -f /root/dockerfiles/ .
Sending build context to Docker daemon  2.56 kB
Error response from daemon: No image was generated. Is your Dockerfile empty?
[root@master dockerfiles]#`

**Comment by kaushalendra-kumar** [comment]
[root@master dockerfiles]# pwd
/root/dockerfiles
[root@master dockerfiles]# ll
total 4
-rwxrwxrwx. 1 root root 577 May 24 10:18 Dockerfile
[root@master dockerfiles]# cat Dockerfile
FROM centos
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
[root@master dockerfiles]# db -t kaushal_centos:1.0 -f /root/dockerfiles/ .
Sending build context to Docker daemon  2.56 kB
Error response from daemon: No image was generated. Is your Dockerfile empty?
[root@master dockerfiles]#

Any idea what is wrong here? Your dockerfile was empty but not mine.

**Comment by ojmarcelino** [comment]
It works on my machine! ¯_(ツ)_/¯
