### ISSUE TITLE
Not backward compatible with Altair BASIC. My machine reboots.

### ISSUE THREAD

**Issue by nicomp42** [kelseyhightower/nocode#2070]
I can't reproduce this, but it happened to me. I didn't write down the error message.

**Comment by dhombs** [comment]
try uninstalling nocode dependencies

**Comment by anushkadoyan** [comment]
fixed

**Comment by nicomp42** [comment]
@anushkadoyan , I didn't run regression tests against your fix but I'm sure it's fine because there were no build errors.
