### ISSUE TITLE
请各位外国网友做点阅读理解。Please foreign readers do some reading comprehension.

### ISSUE THREAD

**Issue by vikingleo** [kelseyhightower/nocode#2076]
为了提高您的中文水平，请阅读以下句子，并回答问题。
1、世界杯赛场上，A国大败B国。
Q：请问A国、B国哪国赢了？

2、世界杯赛场上，A国大胜B国。
Q：请问A国、B国哪国赢了？

3、世界杯赛场上，A国惜败B国。
Q：请问A国、B国哪国赢了？

4、世界杯赛场上，A国惨败B国。
Q：请问A国、B国哪国赢了？

5、世界杯赛场上，A国险败B国。
Q：请问A国、B国哪国赢了？

8、世界杯赛场上，A国险胜B国。
Q：请问A国、B国哪国赢了？

7、世界杯赛场上，A国又败B国。
Q：请问A国、B国哪国赢了？

**Comment by weiyuc** [comment]
why are you so diao
