### ISSUE TITLE
Can't uninstall nocode

### ISSUE THREAD

**Issue by jhakala** [kelseyhightower/nocode#2108]
nocode came preinstalled on my machine and I tried uninstalling by doing
```

```
but I still get:
```

```
Please fix.

**Comment by joshwcorbett** [comment]
This seems to be a common issue among nocode users, and the fix is really quite simple...
Just type in your terminal or cmd:

> 

If the problem persists, then do nothing.

**Comment by jhakala** [comment]
@joshwcorbett thanks for the feedback. I tried your suggestion to `do nothing`. This led to some changes in my philosophical understanding of the meaning of existence; this fixed the issue.

Thanks!
