### ISSUE TITLE
My Name Is ZhaZhaHui, I Will Waiting You In TanWanLanYue 

### ISSUE THREAD

**Issue by nikomal** [kelseyhightower/nocode#2162]
This is a new version that you don not played, if you play it with three minutes, you will like me, love this game!

**Comment by Larry955** [comment]
看到最新issue说why chinese everywhere感觉好丢人...
shame of you all

**Comment by cwdtom** [comment]
兄弟，人家可能只是想表达一下网络上中国人多，你咋就一言不合自己扇自己巴掌了（手动滑稽
@Larry955

**Comment by nikomal** [comment]
@cwdtom someone hate Chinese, not because we are Chinese. here is github. we may discuss or create a issuse by use English. huo zhe ke yi yong ping yin

**Comment by cwdtom** [comment]
照这个言论，是不是微博和所有中国网站都不能有外文？
https://github.com/sentsin/laydate
这种大部分中文介绍的项目是不是没有存在必要？
用什么语言关键在于和你交流的是谁，你要只会英语，那我就和你讲英语~

**Comment by nikomal** [comment]
@cwdtom  但是这里毕竟是别人的仓库, 你要是在echarts国人项目里发中文肯定没啥 ,大家总不至于去人家外国人仓库全用中文交流吧

**Comment by cwdtom** [comment]
我就是知乎观光一下，没事，每个人三观不一样，这种东西也没对错。ojbk~
