### ISSUE TITLE
各位老哥，Springboot启动报内存溢出怎么解决？

### ISSUE THREAD

**Issue by hxiaope** [kelseyhightower/nocode#2216]
如题

**Comment by Imcodingcc** [comment]
You can find the answer below
... 
but no way! hhh

**Comment by nonemaw** [comment]
hi,

I believe the following script can solve your issue

``

Please let me if the above code has any problems

**Comment by Imcodingcc** [comment]
为什么issue里面这么多中国人，皮一下很开心吗？
