### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by dianariyanto** [kelseyhightower/nocode#2268]
Leave a comment

**Comment by MashedPotatoDing** [comment]
// Everywhere

**Comment by scofieldwz** [comment]
in your heart

**Comment by martingaldeca** [comment]
The code is in Narnia, you should go to find it.

**Comment by anoobishnoob** [comment]
The safest way to write code is to not do it

**Comment by dianariyanto** [comment]
Awesome, thanks guys! Now i don't need to fine the code. I'm iron man!
