### ISSUE TITLE
Why Windows 10 isn't named 9?

### ISSUE THREAD

**Issue by devlargs** [kelseyhightower/nocode#2363]

**Comment by countingsort** [comment]
Not related.

Still an answer:  
Windows 95 and 98 are just known as Windows 9 to the programs that run on it (or maybe only the kernel I don't really know).

If they'd release Windows 9 it would break existing software.

**Comment by Ornataweaver** [comment]
Why iPhone X is not named iPhone 9?

**Comment by Ornataweaver** [comment]
You ask to many questions "boy"!

**Comment by devlargs** [comment]
I googled it already. I just want to get along with those silly issues :D thanks

**Comment by kevinjom** [comment]
Because of no code ?
