### ISSUE TITLE
Error Deploying to Raspberry PI

### ISSUE THREAD

**Issue by talhashoaib** [kelseyhightower/nocode#2379]
I am using the following version of UBUNTU on Raspberry PI:
`     `
Now when I run this command:
`    `
Nothing happens. Is the app running in air?

**Comment by smeagolthellama** [comment]
nothing is the expected output.

**Comment by vusonhust** [comment]
You can fix this by using command:
``

**Comment by vusonhust** [comment]
To fix that error, please run command:
`  
`

**Comment by talhashoaib** [comment]
@vusonhust Thank you so much for your help. It is fixed now using your command. Closing the issue.
