### ISSUE TITLE
is no code GDPR compliant?

### ISSUE THREAD

**Issue by laurensmarcelis** [kelseyhightower/nocode#2421]
i do not seem to have gotten a mail from no code to know what is done with my personal information.

**Comment by hydra007** [comment]
Nocode has updated their privacy policy.

**Comment by adamc295** [comment]
**W E ' V E U P D A T E D O U R P R I V A C Y P O L I C Y**

**Comment by thuansoldier** [comment]
**Nocode** is compliant with any industrial security compliance and regulation in the planet. Once you get it deployed, no one can audit it. Everyone accepts **Nocode**.

**Comment by valsekamerplant** [comment]
fair enough
