### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by depfryer** [kelseyhightower/nocode#2451]
i'm new ^^
and when i see all the code i dont really understand the practice 🤔 
if someone have an example, thanks 😄

**Comment by igorvilela28** [comment]
Sure, here's an example

```

```

**Comment by depfryer** [comment]
🤔 but 
```
```
has secure ?

**Comment by narutoo9x** [comment]
It should be like this:
```

```

**Comment by depfryer** [comment]
thanks @narutoo9x
