### ISSUE TITLE
Consider moving to Gitlab?

### ISSUE THREAD

**Issue by alcalyn** [kelseyhightower/nocode#2457]

**Comment by sethmccombs** [comment]
GitLab runs on Azure and is moving to GCP. Moving to GitLab to avoid Microsoft (if that was the point here) hardly avoids "big corporate company"

**Comment by OtacilioN** [comment]
Hmm... No!

**Comment by alcalyn** [comment]
Let's migrate to "the cloud"

**Comment by OtacilioN** [comment]
Which cloud?

**Comment by alcalyn** [comment]
"The" cloud

**Comment by OtacilioN** [comment]
This cloud -> ☁️  ??

**Comment by adamc295** [comment]
How about no cloud!

**Comment by OtacilioN** [comment]
We could share flash drives

**Comment by alcalyn** [comment]
Thanks for not having doing anything, I think the issue is solved now.

**Comment by MeguminSama** [comment]
Please reopen. I think less needs to be done.

**Comment by alcalyn** [comment]
Please open a new issue, or it will take the risk to actually track an issue
