### ISSUE TITLE
Can't open issue #242. No link in issues list provided

### ISSUE THREAD

**Issue by alexlcdee** [kelseyhightower/nocode#247]
Can't open by click. But can open with direct URL modification in browser. Can this be considered as "code required to use product"? 
![image](https://user-images.githubusercontent.com/9890043/35916957-3e031d7a-0c1d-11e8-9b4d-6ae8795e1ac4.png)

**Comment by benbor** [comment]
You can click on "comments icon" on the right side of issue raw.

**Comment by alextartan** [comment]
Issue fixed by adding comments to #242.

you can now click the comments icon and open it.

**Comment by alexlcdee** [comment]
@benbor at the moment of posting my issue, there was no comments (see screenshot attached).

Thanks, now it can be closed.
