### ISSUE TITLE
Nothing happens!

### ISSUE THREAD

**Issue by ItzSomebody** [kelseyhightower/nocode#2508]
When I try to run, nothing happens! PLZ FIX!!!

(Joke issue for those of you who actually thought I was serious)

**Comment by andresroberto** [comment]
that's not a bug but a feature

**Comment by flynnwebdev** [comment]
If nothing happens, then you did everything correctly

**Comment by Ornataweaver** [comment]
Why so serious?

**Comment by pasagir** [comment]
Make a video lesson, please
