### ISSUE TITLE
Zero Factor Authentication issue.

### ISSUE THREAD

**Issue by RyanSkraba** [kelseyhightower/nocode#254]
Use case:

1. I don't install any application on any mobile device.

2. I don't link it by scanning the QR code.

3. I don't enter any password OR the non-existent generated key.

And yet, I still get:

```

```

Is this expected behaviour?

**Comment by RyanSkraba** [comment]
Never mind -- if you skip steps 2, 1 and 3 (in that order), you get: 

```

```

which seems reasonable.

**Comment by adpirz** [comment]
I'm still getting the following output. I didn't run this on a mac:

```

```

Any ideas? I've also not run it on Ubuntu and Debian.
