### ISSUE TITLE
Dockerfile error ...

### ISSUE THREAD

**Issue by Blamo27** [kelseyhightower/nocode#2556]
Dockerfile error please make a support for newer versions

**Comment by Ostap34JS** [comment]
Run this to update:

```

```

**Comment by Blamo27** [comment]
@Ostap34JS Thanks dude !!!!!

**Comment by Blamo27** [comment]
@Ostap34JS WTF still not working

**Comment by Ostap34JS** [comment]
Before updating, you not enabling this? :
```

```

**Comment by Blamo27** [comment]
Sorry, my windows firewall was ON, working now !!!
