### ISSUE TITLE
This code is so fucking bad

### ISSUE THREAD

**Issue by stupidanon** [kelseyhightower/nocode#2559]
It barely even exists

bro what the hell
--

**Comment by FurryCyanFox** [comment]
b̨͍̠̪̲̦͇͓̟͓̪̘̹̰͖̭̰̙̻̦̾ͨͮ͐̈͗ͧͯ̃ͮ̇̋̃̂͑̓ͣ̍́́r̴̸̡̨̡̜͓̜̱͔̹ͨͭ̌̚ơ̻̻͙͚̦̬̫͇̟̰͓̦̤͊͑ͯ̃̎̓ͤ͆̆͘͢ ̝̘̩̮̄̂͐ͫ̈̄̍ͫ̆͛ͨͥ́̚͟w̶͇̼͚̟͕̜͔̥ͩ̋ͮ͒̆̈ͭ̓̆ͤͧ̋ͧ̚͜͡͝h̓̍ͣ͊̋ͨͮ͋ͪͦ̿҉̶̡̟͈̺͚̤̖̥̯̕â̻̹͚̪͙̫̰͖̦͍͇̭̰͍̝͙̗ͦ̐̆̍̈̇ͫ̕̕ͅţ̸̵̇̽̃ͭͯ̌̃͊̔ͣ҉̨̺̜̺ ̷̜̪̖͈̠̌ͩ͌ͫͣ͐̋̃̓͠͡t̸̨̼̟̝͙͇̰̼̠̱̼̙͍̠̺̓ͨ̒ͨ̿͗̓ͯ̇ͦͤ̇ͯ̑ͭ͂ͣ͐͜ḩ̶̢͕͔̖̘̮̣̜̲̻̪̺̲̪̰̰͙̾̓͗́͡ͅȩ͐̎̇ͪ̉ͬ̃ͫ͆ͭͨ̐͝҉̨͚͍̰̦͓ ̷̡̹̠͚̗̟͇͉̗̜̳̥̲̹̍ͯͯͮ̒̇̔̎ͣ͟͡ͅͅh̸̨̢͉̩̮̬̠̟͈̳̞̙̱͈͕̞̯͌̿ͩͬ͋̀̒̓͂͊͋ͦͭ͌̓͞ͅͅe̡̡͍̹̭̪͚̖ͪ̃ͮ̈͐ͩͥ͋̂ͦ̎̌ͬ́͠͠l̖͙̝̮̲̹̙͓̲̪̞̱̼͙̲͚ͫ̌ͤͥ̀̏ͤ̿ͣ̐ͪ͌̀ͫ̉̊̌ͩ̕ļͯ̓ͮ̓͂ͣͤͦ̆̆̑̎͑̊ͣ̍ͫ́́͏̗̰̭̯̜

**Comment by otse** [comment]
̝̘̩̮̄̂͐ͫ̈̄̍ͫ̆͛ͨͥ́̚͟w̶͇̼͚̟͕̜͔̥ͩ̋ͮ͒̆̈ͭ̓̆ͤͧ̋ͧ̚͜͡͝h̓̍ͣ͊̋ͨͮ͋ͪͦ̿҉̶̡̟͈̺͚̤̖̥̯̕â̻̹͚̪͙̫̰͖̦͍͇̭̰͍̝͙̗ͦ̐̆̍̈̇ͫ̕̕ͅţ̸̵̇̽̃ͭͯ̌̃͊̔ͣ҉̨̺̜̺ ̷̜̪̖͈̠̌ͩ͌ͫͣ͐̋̃̓͠͡t̸̨̼̟̝͙͇̰̼̠̱̼̙͍̠̺̓ͨ̒ͨ̿͗̓ͯ̇ͦͤ̇ͯ̑ͭ͂ͣ͐͜ḩ̶̢͕͔̖̘̮̣̜̲̻̪̺̲̪̰̰͙̾̓͗́͡ͅȩ͐̎̇ͪ̉ͬ̃ͫ͆ͭͨ̐͝҉̨͚͍̰̦͓ ̷̡̹̠͚̗̟͇͉̗̜̳̥̲̹̍ͯͯͮ̒̇̔̎ͣ͟͡ͅͅh̸̨̢͉̩̮̬̠̟͈̳̞̙̱͈͕̞̯͌̿ͩͬ͋̀̒̓͂͊͋ͦͭ͌̓͞ͅͅe̡̡͍̹̭̪͚̖ͪ̃ͮ̈͐ͩͥ͋̂ͦ̎̌ͬ́͠͠l̖͙̝̮̲̹̙͓̲̪̞̱̼͙̲͚ͫ̌ͤͥ̀̏ͤ̿ͣ̐ͪ͌̀ͫ̉̊̌ͩ̕ļͯ̓ͮ̓͂ͣͤͦ̆̆̑̎͑̊ͣ̍ͫ́́͏̗̰̭̯̜ b̨͍̠̪̲̦͇͓̟͓̪̘̹̰͖̭̰̙̻̦̾ͨͮ͐̈͗ͧͯ̃ͮ̇̋̃̂͑̓ͣ̍́́r̴̸̡̨̡̜͓̜̱͔̹ͨͭ̌̚ơ̻̻͙͚̦̬̫͇̟̰͓̦̤͊͑ͯ̃̎̓ͤ͆̆͘͢

**Comment by otse** [comment]
How browsers allow those squiggly texts is beyond me
