### ISSUE TITLE
My server is hacked with this method

### ISSUE THREAD

**Issue by doniyor2109** [kelseyhightower/nocode#2613]

**Comment by Geekgee** [comment]
When your server was hacked, what you should do is nothing:)
Because no code, no bugs.

**Comment by ioan-ghisoi-cko** [comment]
I have the same issue, instead of telling you how to do it, here is a link to a post that has the link to a blog that has a video in german with the solution.

**Comment by Geekgee** [comment]
good idea.

**Comment by doniyor2109** [comment]
I upgraded to latest version. Now it is working. Thank you guys 😄
