### ISSUE TITLE
                        Exception

### ISSUE THREAD

**Issue by FastFelix771** [kelseyhightower/nocode#2683]
Hi, i got this strange exception thrown today, while using your library:

Sadly, i cannot imagine from where it comes.
Maybe you can help?
Here is the code of the function that triggers the exception:

Thanks!

**Comment by shrmrf** [comment]
Fixed it:
```

```

**Comment by FastFelix771** [comment]
Ah, i see.
It works great now!
And i didn't even have to change the code. 

Awesome work!
