### ISSUE TITLE
0/0

### ISSUE THREAD

**Issue by narnia1991** [kelseyhightower/nocode#2703]

**Comment by Silicasandwhich** [comment]
Sorry. We can't help you unless you post your hardware specs, OS version, kernel version, terminal font, ASCII art logo of your Linux distribution (if applicable), what IDE you use, who you voted for in 1984, mother's maiden name, where you were on the night of October 23rd, root password to your computer for more inspection, favorite flavor of ice cream, and how you exit vim.

**Comment by Variable-X** [comment]
We also require the year your favorite song's album's main composer's father's year of birth in hexadecimal.
