### ISSUE TITLE
Error on line 0

### ISSUE THREAD

**Issue by mrtnpwn** [kelseyhightower/nocode#2805]
I was building an app with this framework but it seems that I got an error at line 0.

The app is simple: a simple calculator, here's the code:

```nocode

```

I'm using Windows 8.1 with the latest version of nocode.

**Comment by Silicasandwhich** [comment]
Could you post the error?

**Comment by mrtnpwn** [comment]
```nocode

```

I don't know what is happening, the code and everything is fine.

**Comment by Silicasandwhich** [comment]
Ok. I think you're nocode config file got corrupted. If you're on Linux, replace the contents of the file ~/.nocoderc with the provided template. If you're on windows, the file is probably somewhere in %APPDATA%

**Comment by mrtnpwn** [comment]
Oh, that worked! :smile: I guess I should close the issue.
