### ISSUE TITLE
Ubuntu 18.04 stuck on boot loop after installing nocode

### ISSUE THREAD

**Issue by shubham1172** [kelseyhightower/nocode#2870]
After installing the null binary my Ubuntu system is going into a boot loop. I tried logging in via `tty` but `xstart` fails to start.

**Comment by eternaletulf** [comment]
To enable logging you should add ` -- ` first, tell me how it goes after you try this

**Comment by shubham1172** [comment]
I tried logging and here is the output of `cat` :
```






















```
I've no idea what's going wrong!

**Comment by eternaletulf** [comment]
In this line is your problem
 ```

```
I think you should try a clean install of the null binary again
