### ISSUE TITLE
error when using

### ISSUE THREAD

**Issue by KenMizz** [kelseyhightower/nocode#2923]
when I try to do like this
```````
```````
my code just stop working
any solution?

**Comment by alexQi** [comment]
just watching it

**Comment by Subilan** [comment]
@KenMizz Try this

then if you see

that's correct.
But if

that's because something wrong happend during your installation. You can deploy it again.
@ Me when you have the problem again, I will help you in no time :)

**Comment by ScSofts** [comment]
Now you can google  `                                                                                  `  for solutions.
