### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by archiebaer** [kelseyhightower/nocode#3062]
Here is my code:
```
```
When I run it, I get the syntax error:
```
```
It's rather unspecific, what can I do to fix it?

**Comment by Gabgab2003** [comment]
No one does
```

```
You might want to try 
```

```
Instead

**Comment by Rodentman87** [comment]
You also try
```

```
I've found this fix to work much better.

**Comment by archiebaer** [comment]
Thanks. My final code is now:
```
```
I've tested it with a few domains, and it works great!
