### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 1163710106** [kelseyhightower/nocode#3147]

**Comment by 1163710106** [comment]
I am sorry, I am not very understanding of this project.
Is this just a joke?
Or something else, can you explain it to me?

**Comment by wangyuan0217** [comment]
It is what you think it is.

**Comment by izhukovich** [comment]
@1163710106 This is a lifestyle.

**Comment by skjoher** [comment]
@izhukovich na... It's thuglife.

**Comment by 1163710106** [comment]
ok,thanks
