### ISSUE TITLE
Why is this code installed on my computer?

### ISSUE THREAD

**Issue by alex-georgiou** [kelseyhightower/nocode#3162]
I did NOT follow the installation instructions, and yet I found this nocode thing sitting on my computer. It is apparently installed in `/dev/null`, in fact there is a full copy of the entire source code there. How to I uninstall it? It is taking too much of my hard disk space. Please add clear uninstall instructions.

**Comment by alex-georgiou** [comment]
OK, figured it out on my own!

After studying again the readme file, I found that by NOT following the installation instructions I actually DID follow the installation instructions. This is why the code is installed on my computer.

To remove it, I had to do this:
```
```
Then, everything went back to normal:
```
```

**Comment by Ikeetjeop** [comment]
Thanks for sharing, had the same issue, just wanted to clean up my pc.
