### ISSUE TITLE
我的问题如下：

### ISSUE THREAD

**Issue by simsq** [kelseyhightower/nocode#3189]
具体信息如下：

请问该如何解决？

**Comment by HarborZeng** [comment]
调皮

**Comment by KRISACHAN** [comment]
你没看readme吗？
你看这里：

源码有说明原因：
```javascript
```
这里可能有个坑，就是：

所以这么解决就可以了

**Comment by yayapipi** [comment]
解决方法如上

**Comment by sanguigu** [comment]
About it,I have some opinoin:

**Comment by simsq** [comment]
> 你没看readme吗？
> 你看这里：
> 
> 源码有说明原因：
> 
> 这里可能有个坑，就是：
> 
> 所以这么解决就可以了

按照您说的解决了！但是又出现了另外一个问题，报错信息如下：
这个你有遇到过吗？

**Comment by BaochengSu** [comment]
I also run into the exactly same issue:
```
```
please help me!
