### ISSUE TITLE
SegFault when launching my app

### ISSUE THREAD

**Issue by IdkGoodName** [kelseyhightower/nocode#3344]
My code:
```

```
And what I used as command:
```

```
When I do this, I get error `Segmentation Fault`. I tried changing nothing to nothing in my code, but I still get the same error. I think that pointer of nothing causes this in Nocode and therefore, produces Segmentation Fault.

**Comment by azzzure** [comment]
you need an extra declearation in following section
```


```
otherwise compiler may regard ` ㅤㅤㅤ `as   `  ㅤㅤㅤ `which leads to `Segmentation Fault`
In fact you have a better way to do so, just type in 
```
ㅤㅤㅤ
ㅤㅤㅤ
```
