### ISSUE TITLE
就是你宣传无🐎运动？搞得👨现在都不看有🐎了，不够刺激

### ISSUE THREAD

**Issue by xuyifu** [kelseyhightower/nocode#3475]
就是你搞无码运动，号召大家只看欧美，不看日韩，导致有码都衰落了？你是真的牛批，利用p站方便快捷的速度推广无码，别人都说91倒闭都是你造成的，我以前不信，现在看来你还宣传无🐎开源，我有点怀疑了。

**Comment by xueweidiqiu** [comment]
太抽象了2333
