### ISSUE TITLE
？？？完全搞不懂啊 是看片吗 片也要有啊 卧槽 什么莫名其妙的项目，无码就无码 他妈的得有片才能无码啊，不知道一群人在这瞎逼逼什么东西

### ISSUE THREAD

**Issue by GCPD123** [kelseyhightower/nocode#3482]

**Comment by GCPD123** [comment]
来个人说明下啊，都搞得这么隐晦，是不是男人，看个无码的片都搞的这么畏畏缩缩，好东西分享下 怎么他妈的运行

**Comment by xuyifu** [comment]
气急败坏起来了呢？荷尔蒙控制不住了？山东银？
人家就是玩个英语梗，nocode=没有代码=无码。👨👨，你可真是个Fe🍔🍔

**Comment by GCPD123** [comment]
老子也是服了，就这？ 傻逼还真是多

**Comment by liangyiliang** [comment]
这位同志你觉得nocode是什么意思？
是你说的“无码”片的意思么？
马赛克的英文是censoring，不是code。
这位同志

这个项目的特点就是没有任何的代码，也就没有任何的bug。
根据GitHub使用守则，黄色、色情信息是禁止的。
What do you expect?

If you need such "sexual excitements" as uncensored pornography, I'd suggest you to install a VPN and access notable sites such as PH.

**Comment by liangyiliang** [comment]
这个github项目可以运行，输出的结果是"    "。

**Comment by GCPD123** [comment]
我的意思是 没有必要搞这种闹眼子的东西，这有什么意义？ 哗众取宠而已 一群人还自鸣得意 傻逼

**Comment by liangyiliang** [comment]
Something that you may feel meaningful may not be meaningful to others. Something you feel meaningless may be meaningful to others. 

有意义没意义是你说的算么?

**Comment by GCPD123** [comment]
在老子这里 就是老子说了算 我就觉得这没意义就是没意义因为确实没意义 不是没内容吗 那就是没意义 或者说意义没有 这不就是这个傻逼项目要表达的东西嘛 我领会到了吗 所以我喷它也是没有意义 别整这些英文  像傻逼一样

**Comment by MrTallon** [comment]
“别整这些英文 像傻逼一样”。能在GitHub看到这句话，👴i了i了

**Comment by nu11plex** [comment]
兄啊这个项目其实就是这样，没有代码才是代码的最高境界，懂？
