### ISSUE TITLE
What's the purpose of this repo?!

### ISSUE THREAD

**Issue by oneturkmen** [kelseyhightower/nocode#37]

**Comment by spuder** [comment]
Nothing! Please don't read the readme

**Comment by oneturkmen** [comment]
Surprised how many people starred it ...

**Comment by haddigan** [comment]
You must be really fun at parties

**Comment by aarhuuus** [comment]
The purpose of this language is to tame tangles in memory management and providing sufficient security in every code executed. The runtime runs the language in a secure environment layer with no internet access to ensure that no data gets leaked in the process of fulfilling the functions.

This really does change the language game for prioritizing security and memory management.
