### ISSUE TITLE
My code does not build

### ISSUE THREAD

**Issue by wvffle** [kelseyhightower/nocode#3739]
The following chunk of code does not build:
```js

```

I get following error:
```js

```

Please help.

**Comment by hasantayyar** [comment]
Same here.
I am trying to build and run my the container. 
Here are my logs :

```
```

**Comment by gocarlos** [comment]
+1

**Comment by Saucistophe** [comment]
I think I find a workaround by editing the ` `:
I switched from
```
```
to
```
```

Hope this helps!

**Comment by Bobbbay** [comment]
The thing is, you shouldn't have any code. So yeah, @Saucistophe was right, all you need is a bit of:
` `. It really helps. Here's another example: 
```
 
```

**Comment by hasantayyar** [comment]
I am using nothing and I fixed this by doing nothing. Here are the steps 

```
```

**Comment by wpfalive** [comment]
Same here.
I solved  this by staring at the README file for a minute. 
Hope it helps.

**Comment by ssaini123456** [comment]
i have a performance fix, instead of using``   ``
use nolib. 
Example:
```












```
hope this helps

**Comment by wvffle** [comment]
@Saiini that worked! Thanks!
