### ISSUE TITLE
Major issue on ChromeOS

### ISSUE THREAD

**Issue by Bobbbay** [kelseyhightower/nocode#3745]
It's broken. I just get this: 
```
 
```
... after running this:
```
 
```
I wish ChromeOS was easier to use. This is what I want:
```
 
```
All help will be appreciated. Thanks, Bobbbay

**Comment by sanjaykdragon** [comment]
nullptr on line 375

**Comment by cbpudding** [comment]
> nullptr on line 375

How is that possible? There's no code.

**Comment by sanjaykdragon** [comment]
> > nullptr on line 375
> 
> How is that possible? There's no code.

yes, therefore there is null code

**Comment by Bobbbay** [comment]
Ohhh, I understand what's happening now, thanks. Is there any way to fix this?

**Comment by sanjaykdragon** [comment]
> Ohhh, I understand what's happening now, thanks. Is there any way to fix this?

delete line 375

**Comment by Bobbbay** [comment]
Thanks so much!!! Sorry for my late reply. That helps! Here's my code now:
```
 
```
Happy coding, Bobbbay
