### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by Siand** [kelseyhightower/nocode#381]
Hi,
I'm getting an assertion error on line 0, which is the whole code, so it's not very specific and hard to check/fix.
Here's what I'm getting:
Assertion failed on line 0: "no code found at the location."
Any help's appreciated!

**Comment by ctubio** [comment]
let me fix that for you:
```
```

**Comment by Siand** [comment]
What a legend! Wouldn't have thought about that myself.
