### ISSUE TITLE
NoCode Error

### ISSUE THREAD

**Issue by jsaji06** [kelseyhightower/nocode#3818]
I have this code here:
```

```
but it gives me an error:
```

```
How do you fix this?

**Comment by mjnaderi** [comment]
You can use this workaround:

```

```

After applying, your code will run perfectly and print the desired output:

```

```

**Comment by Yehonal** [comment]
It's a duplicate https://github.com/kelseyhightower/nocode/issues/3819

**Comment by jsaji06** [comment]
@mjnaderi No luck. :( I get this "Unsolvable error"

```




```

**Comment by jsaji06** [comment]
Oh wait I'm dumb haha. I just added 
```

```
And then 
```

```

**Comment by mjnaderi** [comment]
@elementzprojects Glad you solved it

**Comment by Charlie-zzy** [comment]
I have the same Error and this helps me out.Thanks!
