### ISSUE TITLE
Unable to auto-scale it on Kubernetes 

### ISSUE THREAD

**Issue by vishnoisuresh** [kelseyhightower/nocode#386]

**Comment by chmduquesne** [comment]
I got it working by adding

`
`

In the environment.

**Comment by hslavchev** [comment]
Can confirm @chmduquesne's fix works. Thanks!

**Comment by vishnoisuresh** [comment]
Thanks, guys. It's working now.

**Comment by rushins** [comment]
how did you do that ?
