### ISSUE TITLE
Can't build on macOS 10.15.4

### ISSUE THREAD

**Issue by vladdenisov** [kelseyhightower/nocode#3862]
I've installed xcode and tried to build using this command 
``` 

```
But it didn't work. So I've added this lines
```



```
```






```
Now it partly works.

**Comment by Azuelle** [comment]
try this maybe
```


```
if it still doesn't work, try restarting your computer

**Comment by vladdenisov** [comment]
Thank you for reply, @TjkFred 
I've tried your code.
Here's the log: 
```




















































```
Doesn't even boot now. Kernel panic.

**Comment by AntonKukoba1** [comment]
> I've installed xcode 

That was the issue. It should be built with this toolchain:

**Comment by Lg0gs** [comment]
@TjkFred Worked for me. Thanks!

**Comment by vladdenisov** [comment]
>  That was the issue. It should be built with this toolchain:

Thanks. I will try it now.

**Comment by chefnobody** [comment]
Did you talk to DevOps?
