### ISSUE TITLE
Help! Does not work on Apple II

### ISSUE THREAD

**Issue by harshitm98** [kelseyhightower/nocode#3871]
This is the error message displayed while running the code:

**Comment by acerspyro** [comment]
Works perfectly here, I don't know what you're doing that you shouldn't be doing.

**Comment by zjeffer** [comment]
Have you tried turning it off and on again?

**Comment by harshitm98** [comment]
NVM, I figured it out.

**Comment by acerspyro** [comment]
![image](https://user-images.githubusercontent.com/4400999/75907691-bbb95c00-5e16-11ea-8b66-98e2f79714f3.png)
