### ISSUE TITLE
Add COVID19 antivirus support

### ISSUE THREAD

**Issue by Masterxhen** [kelseyhightower/nocode#3954]
Please add anti-virus support for the corona virus (CoVid19) pandemic

**Comment by MengelCode** [comment]
Deployment output:

Release Notes:

All done.

**Comment by gensjaak** [comment]
Anti-virus still not working for EU zone. Have a patch to solve that ? Or need a VPN ?

**Comment by MengelCode** [comment]
Submitted a hotfix. Please test again.

**Comment by Masterxhen** [comment]
Damn It works :D
