### ISSUE TITLE
问下，是真没有可运行的demo和功能，点赞只是调侃是吧

### ISSUE THREAD

**Issue by macqueen09** [kelseyhightower/nocode#3975]
我确认下，大家Top-1的项目，看了一会没有可运行的demo和实际功能，点赞和Issues只是调侃是吧？？
我担心调侃太多以至于实际上是真有功能，只是我自己不会用没找到地方而已。
也替相同萌新排坑，严肃的问。

**Comment by Kiprey** [comment]
是

**Comment by macqueen09** [comment]
竟然真是这样。。。
大家可真是摸鱼高手，告辞

**Comment by songjiachao** [comment]
你还没悟道
