### ISSUE TITLE
Critical issue: Unable to get any output.

### ISSUE THREAD

**Issue by mroyme** [kelseyhightower/nocode#4274]
Hi, 
I'm trying to deploy this application nowhere and the program isn't yielding any output.

I have followed the read me and tried running the following command:
```

````

I even tried removing the extra command line arguments.

It's on version` `.

Enabling debugging mode, I can see the following in the log files:

```

````
Please help.

**Comment by JinmengRao** [comment]
Based on the log content, I am pretty sure it is caused by ` `. Did you try ` `?
If it still doesn't work, please try the following command:
```
```

**Comment by Xezeloh** [comment]
> Based on the log content, I am pretty sure it is caused by ` `. Did you try ` `?
> If it still doesn't work, please try the following command:

That works! Thx!

**Comment by xeor** [comment]
Can we close this then?

**Comment by mroyme** [comment]
Yes, thanks a lot, everyone. I'm not sure how I missed that. Anyway, I'm closing the issue. 
Thanks, again
