### ISSUE TITLE
A Very Serious Bug

### ISSUE THREAD

**Issue by liu-yunfei** [kelseyhightower/nocode#4277]
Hello!

I have found a very serious bug, which may lead to PROBLEMS!!! The detail is provided below:
> 
> 
> 
> 
Please fix it soon!!!! Thank you.

**Comment by aschao** [comment]
hi,this bug has fixed,please restart again

**Comment by liu-yunfei** [comment]
Hello!

I restarted the program, but it shows `                                         ` 

I don't know how to deal with it, would you mind to help me with that?

Thank you~~~

**Comment by newcardriver** [comment]
> Hello!
> 
> I restarted the program, but it shows ` `
> 
> I don't know how to deal with it, would you mind to help me with that?
> 
> Thank you~~~

may be you need reboot your noPhone !

**Comment by liu-yunfei** [comment]
> > Hello!
> > I restarted the program, but it shows ` `
> > I don't know how to deal with it, would you mind to help me with that?
> > Thank you~~~
> 
> may be you need reboot your noPhone !

Oh yes, it works well now. Thank you.
