### ISSUE TITLE
No issue that causes no issue that does not start a race condition that is not reproducible

### ISSUE THREAD

**Issue by PathToLife** [kelseyhightower/nocode#4340]
No issue that causes no issue that causes an issue with AI auto issue categorization.

to summaries:
no issue that causes no issues

in Hungarian because no one asked:
nincs olyan kérdés, amely nem okoz problémát

**Comment by 0o10** [comment]
I was unable to produce this on my MacBook Pro. 
Testing on a Windows 10 laptop now.

**Comment by 0o10** [comment]
Alright so it appears that the no issue is isolated to windows.
I will be able to run more thorough tests in a second.

**Comment by Hocuri** [comment]
Now this issue hasn't got any activity for 2 hours. I vote to close it as stale.

**Comment by PathToLife** [comment]
closing because issue was fixed with no changes required. Thus there was no reason to have this issue in the first place
