### ISSUE TITLE
Can't build app to Android

### ISSUE THREAD

**Issue by tpsouza48** [kelseyhightower/nocode#4341]
I tried this options when building:
`                                        `
It did not work. Any workarounds?

**Comment by abcdan** [comment]
Try to ` `!

**Comment by tpsouza48** [comment]
That may solve it, gonna test it and reply the results here.

**Comment by tpsouza48** [comment]
Sadly, it didn't work, now the error is:
`                 `
And i still can't build it :/

**Comment by tpsouza48** [comment]
I figured it out! The build was failing because `    `   was set to  `   `  instead of  `   `! Closing this issue now!
