### ISSUE TITLE
Help! Can't get decent performance on Java

### ISSUE THREAD

**Issue by ojmarcelino** [kelseyhightower/nocode#4536]
Hi, I've been trying for a bunch of weeks, to compile a nice and clean implementation, but always stuck on memory issues using JDK. Damn, I just tried a lot of other options and the final no code would be like this

Code:

Error:

Has anyone tried that before?

**Comment by ahpxex** [comment]
try this:
```

```

**Comment by mantikafasi** [comment]
> try this:
> ```
> 
> ```

That worked for me, Thanks

**Comment by ojmarcelino** [comment]
> > try this:
> > ```
> > 
> > ```
> 
> That worked for me, Thanks

SLTM

**Comment by ojmarcelino** [comment]
> > try this:
> > ```
> > 
> > ```
> 
> That worked for me, Thanks

SLTM
