### ISSUE TITLE
I'm not having any problem. Can someone help?

### ISSUE THREAD

**Issue by astravaganza** [kelseyhightower/nocode#4541]
title

**Comment by ojmarcelino** [comment]
if you could provide some MWE or any other implementation, maybe we can. In any cases whatsoever, I'll start by using something like this:
`
`
It works on my machine!

**Comment by ramiromagno** [comment]
Also working here:

```
```

**Comment by LucienShui** [comment]
```
```

**Comment by Tarek-Bohdima** [comment]
this should be marked as duplicate of nothing

**Comment by tj-commits** [comment]
It is not supposed to throw an error. it's supposed to work. if you want your code to have an error, just create a syntax error like this:
```
                      
 
  


 
 
 
```
As we can see, line 4 has a syntax error. if you want it to have an error, just create one. it's that easy.
