### ISSUE TITLE
​

### ISSUE THREAD

**Issue by donno2048** [kelseyhightower/nocode#4600]
​​​​​​​​​​​​​​​​​​​​

**Comment by sb-child** [comment]
```

```

**Comment by Khuirul-Huda** [comment]
Oh yeah #4600

**Comment by hahaxiaowai** [comment]
```
```

**Comment by AlfonsoFR2020** [comment]
Sorry, but from our perspective, we can not completely agree on that point. It should be something more like:
`

`
I'm hoping that clarifies the issue at hand.

**Comment by donno2048** [comment]
Closing as stale
