### ISSUE TITLE
I need a therapist. Is nocode sentient yet?

### ISSUE THREAD

**Issue by rolandixor** [kelseyhightower/nocode#4604]
Thanks.

**Comment by ig0rsky** [comment]
@rolandixor how can I _not_ help you?

**Comment by rolandixor** [comment]
> @rolandixor how can I _not_ help you?

Thanks. This solved my problems and I finally quit drinking the drank.

**Comment by ig0rsky** [comment]
I'm happy I _didn't_ help you solve your problem @rolandixor.
