### ISSUE TITLE
The real purpose of nocode

### ISSUE THREAD

**Issue by visma-marko-parkkola** [kelseyhightower/nocode#4639]
If we think of a machine that _does not do nothing_, it is quite easy. It just doesn't do nothing. But a machine that _does nothing_ is much, much harder concept. It is a machine that actually does something in order to transform everything to nothing. This was the problem Trurl and Klapaucius found out that if you create a machine to does nothing, it will start to transform everything to nothingness. (you can find more info in Stanislaw Lem's The Cyberiad)

So is the purpose of nocode just to do nothing or to turn all code to nothing?

I'm hoping for latter.

**Comment by AlfonsoFR2020** [comment]
Thank you for the reference, we all love good ol' uncle Lem.
Regarding your sharp observation, IMHO it seems in fact that `nocode` -must- **do nothing**, and that turning everything around it into nothingness is a side effect. It is still unclear though if this side effect is of the desirable or of the undesirable kind.
An alternative approach is for `nocode` to just -**not do**-, thus avoiding the collateral voiding of Reality that occurs when simply doing nothing. This of course causes troubles in our coding pipeline when handling double negations, as we should not just "not do anything", but, again, just "do nothing". We are working on these issues by not working on them, and will keep you posted with any outcomes we encounter, -or not-.
