### ISSUE TITLE
I got a no error in the no compiler. Help

### ISSUE THREAD

**Issue by BOB450** [kelseyhightower/nocode#4728]
Hope you can find a fix might need to remove more code.

**Comment by toydotgame** [comment]
Try removing line 0 too?
Might as well spoon-feed this one:
```
```
If that doesn't work, try deleting the project and don't start again.

**Comment by BOB450** [comment]
I'll give that a try thanks

**Comment by AlfonsoFR2020** [comment]
> If that doesn't work, try deleting the project and don't start again.

Thanks a lot, that tip worked marvelously for us!

**Comment by BOB450** [comment]
Ya I just needed to delete my project then write over it with a terabyte of data. Thanks guys

**Comment by hausofliufeng** [comment]
Thanks, this totally solved my problem!

**Comment by BOB450** [comment]
No problem.
