### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zeriaxdev** [kelseyhightower/nocode#4798]
When I compile this code:
```nocode
 
```

Compiler crashes and the program doesn't work. :(
This is the error I get:
```bash
 
```

Is there a way to fix this?

**Comment by ghost** [comment]
That's been a recent bug introduced from the 3.7 update.

You need to put 

`                                                                                                                 `
and that should work

**Comment by zeriaxdev** [comment]
Thanks, PartyPenny! Now it's working perfectly!

**Comment by shatindle** [comment]
Ran into this the other day.  Thanks for finding this!

**Comment by HoseanRC** [comment]
had to use `‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ `‌ when working with this bug, now it's fixed! Thanks.

Here is the log if you're curious:
```
‌
‌
‌
‌
‌
‌
‌
```
