### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by havardox** [kelseyhightower/nocode#4828]
Last commit was Jan 21 2020. Did the maintainer just abandon this project?

If so, I'm quite disappointed. I personally know lots of people whose code is dependant on this. The developer can't just leave like that.

**Comment by alex067** [comment]
The state of this industry, smh

**Comment by alysonfarias** [comment]
⠀

**Comment by joao-rafael** [comment]
```

```

**Comment by havardox** [comment]
>

**Comment by toydotgame** [comment]
​
