### ISSUE TITLE
chrome://kill/

### ISSUE THREAD

**Issue by 70CentsApple** [kelseyhightower/nocode#5039]
关注`V在燃烧`谢谢喵，关注`V在燃烧`谢谢喵

https://user-images.githubusercontent.com/63957117/215661497-4346e8c0-7f6a-4911-9553-063ae4136917.mp4

**Comment by 70CentsApple** [comment]
Please subscribe to `V在燃烧`, please subscribe to `V在燃烧`

**Comment by YaoSiQian** [comment]
> 关注`V在燃烧`谢谢喵，关注`V在燃烧`谢谢喵
> 
> 
> 
> https://user-images.githubusercontent.com/63957117/215661497-4346e8c0-7f6a-4911-9553-063ae4136917.mp4
> 
> 
> 
> 

不如**《Zood》**
