### ISSUE TITLE
[Python]AttributeError: 'int' object has no attribute 'close'

### ISSUE THREAD

**Issue by Ealsen** [kelseyhightower/nocode#5093]
# my python code:
def writefile_save(file_name):
    try:
        f = None
        f = open(file_name, mode='a', encoding='UTF-8')
        content = str(input("输入你保存的文字:"))
        f = f.write(f"\t{content}")
    except Exception as e:
        print("程序错误，原因是：{e}")
    finally:
        if f:
            f.close()

if __name__ == '__main__':
    writefile_save("test1.txt")    

# run:
PS G:\Work_Room\python_code> & "C:/Program Files/Python310/python.exe" g:/Work_Room/python_code/writefilesave.py
输入你保存的文字:wj
Traceback (most recent call last):
  File "g:\Work_Room\python_code\writefilesave.py", line 14, in <module>
    writefile_save("test1.txt")
  File "g:\Work_Room\python_code\writefilesave.py", line 11, in writefile_save
    f.close()
AttributeError: 'int' object has no attribute 'close'
PS G:\Work_Room\python_code>

# q:
what do?

以上报错了，怎么解决

**Comment by Heliodex** [comment]
Try removing some of the code.
