### ISSUE TITLE
SSL Support with Unity?

### ISSUE THREAD

**Issue by knightbenax** [kelseyhightower/nocode#521]
I am trying to run this on Unity with SSL support. No luck. Any ideas?

**Comment by AlexSwensen** [comment]
I think i can help you. Just run the following:
```
```

You should get an output similar to 
```
```
if that happens, you are all set!

**Comment by knightbenax** [comment]
Omg you are lifesaver. I absolutely tried nothing, just like you suggested and it worked. Everything is perfectly not running fine now.
