### ISSUE TITLE
Please add .gitignore to avoid committing any code by mistake

### ISSUE THREAD

**Issue by fabiosussetto** [kelseyhightower/nocode#795]
I was working on nothing and I accidentally tried to commit a file with some code in it to the repo.
I think we should add a .gitignore file to prevent this kind of mistakes.
It should look like this:

```
*
*/
```
I'd happily open a PR if no one is interested in this.

**Comment by Omicron666** [comment]
This is error prone. How would ignore this file itself if you don't plan to commit anything ?

**Comment by fabiosussetto** [comment]
> This is error prone. How would you ignore this file itself if you don't plan to commit anything ?

You are right. Better do nothing in this case, as usual.

**Comment by above-c-level** [comment]
‌‌

**Comment by keligijus** [comment]
```

```

- 
-
-
