### ISSUE TITLE
Please support people who are colorblind

### ISSUE THREAD

**Issue by MarkRebuck** [kelseyhightower/nocode#809]
I, like many other people, am red/green/brown colorblind.  The current colorscheme is just *horrible*.  Please avoid all use of red, greed, or brown, and provide a purely greyscale option.

Also, failure to accommodate colorblind individuals is a violation of the Americans with Disabilities Act of 1990, 42 U.S.C.: Public Health and Social Welfare (42 U.S.C. ch. 126 § 12101 et seq).  Nocode is therefore not usable for any of my public sector clients.

**Comment by jasonmemez** [comment]
Run this command to use a version for the colorblind:
```

```
And you're set!

**Comment by MarkRebuck** [comment]
Worked!   I feel silly for not trying that first.  Closing.
