### ISSUE TITLE
Use the blockchain

### ISSUE THREAD

**Issue by nathan-osman** [kelseyhightower/nocode#81]
This is 2018.

Therefore to remain relevant, this project must use the blockchain. Yes, THE blockchain.

I have no idea what this means, what this looks like, or where to begin but the contributing guidelines specifically instruct contributors not to write code, so I didn't. You're welcome.

**Comment by petermbenjamin** [comment]
This project already supports blockchain as of v1.0.0.
Check the release notes: https://github.com/kelseyhightower/nocode/releases/tag/1.0.0
