### ISSUE TITLE
Bootstrapping nocode

### ISSUE THREAD

**Issue by rvillablanca** [kelseyhightower/nocode#892]
I don't know what languages are used to build this amazing app but it seems there are to many bugs with this version of nocode so,  would be possible to rewrite a new nocode version with nocode ? This would improve the performance and would be more easy to maintain.

**Comment by devios1** [comment]
Actually NoCode is a member of an exclusive class of programs known as self-inclusive totalities. In short, any NoCode program is also _every_ NoCode program, meaning that by writing just one NoCode program you've also written every possible NoCode program.

So NoCode is already written in itself, and it's already as efficient as it can be.

I do, however, suggest changing line 0 of the source code from:

``

To:

``

Surely that was just an oversight.

**Comment by rvillablanca** [comment]
Wow NoCode is amazing
