### ISSUE TITLE
Keeps dropping connection

### ISSUE THREAD

**Issue by ItsJosh18** [kelseyhightower/nocode#905]
Every time I request something it drops the connection

**Comment by Dillybob1992** [comment]
Hi @ItsJosh18, thanks for your report.

Unfortunately, I don't think there is anything we can do about this. 
Kind regards,
--Dilly

**Comment by topherhooper** [comment]
@itsjosh18, I ran into the problem too. Have you tried having no requests? This should take care of any connections issue!

**Comment by ItsJosh18** [comment]
@topherhooper I did not. Thanks for the tip works like a charm now.
