### ISSUE TITLE
Wired bugs, can anybody help me?

### ISSUE THREAD

**Issue by XenonChau** [kelseyhightower/nocode#949]
**Platform:**
```

```
**Environment:** 
```
# Python



# Java



# Ruby



# Golang



```

_**Here is the error output:**_

```




```

I tried these ways to fix it, but it's seem useless.

**First**
```





```
**Second**
```


```
**Then**
```

```

There were lots of solutions in StackOverFlow:

[Question:0 - StackOverFlow ](#)
[Question:1 - StackOverFlow ](#)
[Question:2 - StackOverFlow ](#)
[Question:3 - StackOverFlow ](#)

But none of them can fix my issues...

Thanks for your help.
Best regards!

**Comment by rdev** [comment]
I think the error is in your environment config. Try changing 

```
# Python



# Java



# Ruby



# Golang



```

to this:

```
















```

**Comment by XenonChau** [comment]
Thx, I'll have a try. @rdev

**Comment by XenonChau** [comment]
@rdev 
### Year, it works for me!
the again.
