### ISSUE TITLE
Can we rewrite it in Rust? 

### ISSUE THREAD

**Issue by kiloreux** [kelseyhightower/nocode#98]
I have been experiencing performance issues on Ubuntu Linux 16.04. Are there any plans to rewrite it in Rust?

**Comment by recursor94** [comment]
Nocode is actually language agnostic--that's part of it's elegance.

It's the only program whose source is exactly the same in every single language, whether interpreted or compiled.

**Comment by softprops** [comment]
As a result it also runs pretty close to the metal so it's likely to solve a wide variety of performance bottlenecks in production.

**Comment by wfraser** [comment]
It's already written in rust, you just need to build it manually:

    > git clone https://github.com/kelseyhightower/nocode && cd nocode
    > touch nothing.rs
    > rustc --crate-type=lib nothing.rs
    > ls -al libnothing.rlib
    -rw-r--r-- 1 wfraser wfraser 2872 Feb  6 23:16 libnothing.rlib
